### ISSUE TITLE
Dragging an element, infinite loop

### ISSUE THREAD

**Issue by ccorcos** [paldepind/flyd#26]
I made a pen demonstrating the problem:

http://codepen.io/ccorcos/pen/OVpLPv?editors=101

I'm not sure why I'm getting an infinite loop here. Note that I've flipped the order of takeUntil. It seems to make more sense to me. So you can say `takeUntilEnd = takeUntil(end)` if its properly curried. 

Anyways, I have no idea why theres this infinite loop. Theres no problem when I remove the inner map...

```js
var start = flyd.stream();
var move = flyd.stream();
var end = flyd.stream();

var $elem = $('.drag');
$elem.on('mousedown', R.pipe(R.prop('pageX'), start));
$elem.on('mousemove', R.pipe(R.prop('pageX'), move));
$elem.on('mouseup', R.pipe(R.prop('pageX'), end));

function takeUntil(term, src) {
  return flyd.endsOn(flyd.merge(term, src.end), flyd.stream([src], function(self) {
    self(src());
  }));
};
  
flyd.map(function(x) {
  console.log("start", x)
  var offset = $elem.position().left - x;
  flyd.map(function(x) {
    console.log("move", x)
    $elem.css('translateX', x-offset)
  }, takeUntil(end, move));
}, start);
```

**Comment by paldepind** [comment]
I've fixed the infinite loop. [See here](http://codepen.io/anon/pen/EjWGNO?editors=001). There is still a bug left though. I'll have to take a look at that as well.

Anyway, I think you should try a solution a bit like this:

```javascript
var mouseDown = flyd.stream();
var mousePos = flyd.stream();

var $elem = $('.drag');
$elem.on('mousedown', R.pipe(R.T, mouseDown));
$elem.on('mouseup', R.pipe(R.F, mouseDown));
$(document).on('mousemove', R.pipe(R.prop('pageX'), move));

var downAt = sampleOn(mouseDown, mousePos);
var downMoves = keepWhen(mouseDown, mousePos);

lift(function(start, cur) {
  console.log('difference', cur - cur)
}, downAt, downMoves)
```

It completely avoids creating streams at runtime.

**Comment by ccorcos** [comment]
Hmm. So its still not entirely working. The inner map is unhappy. I've placed some log statements and its clear that the inner map should be firing, but its not.

http://codepen.io/ccorcos/pen/xGqBWW?editors=011

I've also added some CSS to the body and made sure to listen to mouse move and mouse up on the body because you can drag off the element quickly.

I like your style you mentioned above. Things are going to get a tricky though if you want to keep track of the offset of the click, and the speed of the drag like in this example:

https://github.com/ccorcos/meteor-tracker-streams/blob/master/examples/slide-menu/client/main.coffee#L91

I suppose we'd just have to do a scan over that lifted stream. Resolving on the mouseup could be challenging as well...

**Comment by paldepind** [comment]
Yes. As I mentioned there is still a bug left.

I am not sure why those cases would get tricky or how the other solution would solve it better? But generally I think there is value in creating as few streams as possible. It keeps things simpler.

**Comment by paldepind** [comment]
@ccorcos Try your codepen again! It should work now. I'm sorry it took me so long to get around to fix this issue.

This bug was sadly introduced as part of the latest optimizations. It's now covered by test cases so I promise it wont happen again ;)

Thank you for reporting this! (And if I'm mistaken at this is not fixed for you – please reopen).

**Comment by ccorcos** [comment]
sweet! thanks
